### ISSUE TITLE
Values of the first level ObservationUnit ID is not correctly registered

### ISSUE THREAD

**Issue by cpommier** [elixir-europe/plant-brapi-to-isa#67]
Instead of the following:
```
observationLevels[BLOCK]	observationLevels[BLOCK>PLOT>PLANT]	observationLevels[BLOCK>PLOT]	observationUnitName	
		BLOCK>PLOT	26515.13	gnpis.lot:'0009D'
```
we should have something like:
```
observationLevels[BLOCK]	observationLevels[BLOCK>PLOT>PLANT]	observationLevels[BLOCK>PLOT]	observationUnitName	
1	45	26515.13	26515.13	gnpis.lot:'0009D'
```

with that parameters call:
-e https://urgi.versailles.inra.fr/faidare/brapi/v1/ -J -V -s dXJuOlVSR0kvc3R1ZHkvUklHVzE=

**Comment by bedroesb** [comment]
hmm interesting, let me try to reconstruct this

**Comment by bedroesb** [comment]
I got a fix with outcome:

observationLevels[BLOCK>PLOT] | observationLevels[BLOCK>PLOT>PLANT] | observationLevels[BLOCK] | observationUnitName | observationUnitXref | X | Y | germplasmDbId
-- | -- | -- | -- | -- | -- | -- | --
26515 | 26515.13 | 1 | 26515.13 | gnpis.lot:'0009D' | 22 | 13 | aHR0cHM6Ly9kb2kub3JnLzEwLjE1NDU0L09EUE1KTg==
26515 | 26515.13 | 1 | 26515.13 | gnpis.lot:'0009D' | 22 | 13 | aHR0cHM6Ly9kb2kub3JnLzEwLjE1NDU0L09EUE1KTg==
26515 | 26515.13 | 1 | 26515.13 | gnpis.lot:'0009D' | 22 | 13 | aHR0cHM6Ly9kb2kub3JnLzEwLjE1NDU0L09EUE1KTg==
26515 | 26515.13 | 1 | 26515.13 | gnpis.lot:'0009D' | 22 | 13 | aHR0cHM6Ly9kb2kub3JnLzEwLjE1NDU0L09EUE1KTg==
26515 | 26515.13 | 1 | 26515.13 | gnpis.lot:'0009D' | 22 | 13 | aHR0cHM6Ly9kb2kub3JnLzEwLjE1NDU0L09EUE1KTg==

Was a stupid bug in the code, obslvl instead of obslvls  :)
